// Example generated by ChatGPT using grammar.ohm as input.

/*
 * This defines a marketplace API.
 * It's very verbose and non-sensical but stress most of Katschema features and
 * is useful to see how a real-world definition would look like.
 */

{
  "version": 1,
  "service": "shopping-api",
  "defaults": {
    "currency": "USD",
    "country": "US"
  },

  "types": {
    "money": {
      "amount": (float, x >= 0),
      "currency": (string, len(x) == 3)
    },

	// address is a global address then most of its field are optional due to country differences.
    "address": {
      "name": (string, len(x) >= 3),
      "street": (string),
      "number": (string, optional),
      "complement": (string, optional),
      "district": (string, optional),
      "city": (string, optional),
      "state": (string, optional),
      "country": (string),
      "zipcode": (string, len(x) > 0)
    },

    "user": {
      "id": (string, uuid(x), pk),
      "email": (string, email(x), unique),
      "name": (string, len(x) >= 3, len(x) <= 120),
      "role": (string,
        x in [
          "customer",
          "admin",
          "support"
        ]
      ),
      "status": (string,
        x in [
          "active",
          "disabled",
          "pending"
        ]
      ),
      "birthday": (string, optional),
      "phones": [(string, x ~ "^\\+[1-9][0-9]{7,14}$")],
      "default_shipping": (.types.address, optional),
      "created_at": (datetime),
      "updated_at": (datetime)
    },

    "category": {
      "id": (string, uuid(x)),
      "slug": (
        string,
        x ~ "^[a-z0-9-]+$"
      ),
      "name": (string)
    },

    "product": {
      "id": (string, uuid(x), pk),

      "sku": (
        string,
        startsWith(x, "SKU-"),
        len(x) <= 32,
        unique
      ),

      "name": (
        string,
        len(x) >= 3,
        len(x) <= 200
      ),

      "slug": (
        string,
        x ~ "^[a-z0-9-]+$"
      ),

      "description": (
        string,
        optional
      ),

      "category": (
        .types.category
      ),

      "price": (
        .types.money
      ),

      "cost": (
        .types.money,
        internal
      ),

      "inventory": {
        "quantity": (
          int,
          x >= 0
        ),

        "reserved": (
          int,
          x >= 0
        ),

        "track": (
          bool
        )
      },

      "dimensions": {
        "width_cm": (
          number,
          x > 0
        ),
        "height_cm": (
          number,
          x > 0
        ),
        "depth_cm": (
          number,
          x > 0
        ),
        "weight_kg": (
          number,
          x > 0
        )
      },

      "images": [
        (
          string,
          url(x)
        )
      ],

      "tags": [
        (
          string,
          len(x) >= 2
        )
      ],

      "status": (
        string,
        x in [
          "draft",
          "active",
          "archived"
        ]
      )
    },

    "cart_item": {
      "product": (
        .types.product
      ),

      "quantity": (
        int,
        x > 0
      )
    },

    "payment": {

      "method": (
        string,
        x in [
          "credit_card",
          "pix",
          "paypal",
          "bank_transfer"
        ]
      ),

      "status": (
        string,
        x in [
          "pending",
          "authorized",
          "captured",
          "failed",
          "refunded"
        ]
      ),

      "transaction_id": (
        string,
        optional
      ),

      "amount": (
        .types.money
      )
    },

    "shipment": {

      "carrier": (string),

      "tracking_number": (
        string,
        optional
      ),

      "status": (
        string,
        x in [
          "pending",
          "processing",
          "shipped",
          "delivered",
          "returned"
        ]
      ),

      "shipping_address": (
        .types.address
      )
    },

    "order_item": {

      "product_id": (
        string,
        uuid(x)
      ),

      "name": (
        string
      ),

      "sku": (
        string
      ),

      "unit_price": (
        .types.money
      ),

      "quantity": (
        int,
        x > 0
      ),

      "subtotal": (
        .types.money
      )
    },

    "order": {

      "id": (
        string,
        uuid(x),
        pk
      ),

      "number": (
        string,
        startsWith(x, "ORD-"),
        unique
      ),

      "customer": (
        .types.user
      ),

      "items": [
        (
          .types.order_item
        )
      ],

      "payment": (
        .types.payment
      ),

      "shipment": (
        .types.shipment
      ),

      "subtotal": (
        .types.money
      ),

      "shipping_cost": (
        .types.money
      ),

      "discount": (
        .types.money
      ),

      "total": (
        .types.money
      ),

      "coupon": (
        string,
        optional
      ),

      "notes": (
        string,
        optional,
        len(x) <= 500
      ),

      "status": (
        string,
        x in [
          "pending",
          "paid",
          "processing",
          "shipped",
          "completed",
          "cancelled",
          "refunded"
        ]
      ),
      "created_at": (datetime),
      "updated_at": (datetime)
    }
  },

  "endpoints": {
	// Returns a list of products.
    "GET /products": {
      "response": [
        (.types.product)
      ]
    },

	// Returns a product by id.
    "GET /products/:id": {
      "response": (.types.product)
    },

	// Create an order.
    "POST /orders": {

      "request": {
        "customer_id": (
          string,
          uuid(x)
        ),
        "items": [
          {
            "product_id": (
              string,
              uuid(x)
            ),
            "quantity": (
              int,
              x > 0
            )
          }
        ],

        "coupon": (
          string,
          optional
        )
      },
      "response": (.types.order)
    },

    "GET /orders/:id": {
      "response": (.types.order)
    }
  }
}
