name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Testing
        run: go test ./... -timeout 60s -race -shuffle on

  grammar-validation:
    name: Validate Ohm Grammar Examples
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: setup nodejs
        uses: actions/setup-node@v7
        with:
          node-version-file: 'grammar/package.json'
          cache-dependency-path: 'grammar/package-lock.json'
          cache: npm

      - name: Install validator dependencies
        run: cd grammar && npm ci

      - name: Check examples using grammar.
        run: make check/grammar
